### ISSUE TITLE
Breaks play's 'eclipsify' command

### ISSUE THREAD

**Issue by eamelink** [lunatech-labs/play-module-resteasy#2]
After adding resteasy to the module configuration with module.resteasy=${play.path}/modules/resteasy-1.3.1, the 'play eclipsify' command fails, with the following error:

Traceback (most recent call last):
  File "/home/eamelink/bin/play", line 111, in <module>
    cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "/home/eamelink/opt/play-1.1.1/framework/pym/play/commands/eclipse.py", line 108, in execute
    execfile(commands)
  File "/home/eamelink/opt/play-1.1.1/modules/resteasy-1.3.1/commands.py", line 5, in <module>
    if play_command == 'hello':
NameError: name 'play_command' is not defined

**Comment by francisdb** [comment]
I have the same issue

Error while loading /home/francisdb/workspace/carambla/caramblaplay/modules/resteasy-1.3.1/commands.py: name 'play_command' is not defined

importing the project in eclipse still works though

**Comment by jagregory** [comment]
I'm seeing this too with the `idealize` and `dependencies` commands. If you delete `modules/resteasy-1.3.1/commands.py`, it should work (as the file doesn't have any commands defined anyway). Sadly, as soon as you run `dependencies` again, it comes back.

Fix: Just delete `commands.py` or implement it properly.
